public/manifest.json
src/App.js
src/components/Footer.js
src/components/Header.js
src/pages/Login.js
src/pages/Main.js
src/pages/Signup.js
src/shared/Cookie.js
src/shared/api.js
src/shared/regExp.js

0726 기본 설정

---

src/components/Category.js
src/components/Header.js
src/pages/Main.js
src/redux/modules/user.js
src/shared/Cookie.js
src/shared/api.js

login check ok

---

src/components/Category.js
src/components/Header.js
src/pages/Main.js
src/redux/modules/main.js
src/redux/modules/user.js

header update

---

src/App.js
src/components/CreateImgSelect.js
src/pages/ChallengeCreate.js
src/pages/Mypage.js
src/redux/modules/challengeCreate.js
src/redux/modules/mypage.js
src/shared/api.js
yarn.lock

챌린지 개설 페이지에서 개설 항목이 비어있을 경우 경고문을 띄워주는 코드 추가

[merge] 챌린지 개설 조건에 따른 경고문

---

src/components/Category.js
src/components/Header.js
src/components/MainSlider.js
src/pages/Main.js
yarn.lock

update main page

---

.gitignore
src/components/ChallengesInProgress.js
src/components/CompletedChallenge.js
src/components/MyPassword.js
src/components/MyPieces.js
src/components/UpcomingChallenge.js
src/pages/Login.js
src/pages/Mypage.js
src/pages/Signup.js
src/redux/configureStore.js
src/redux/modules/challengeCreate.js
src/redux/modules/mypage.js
src/shared/api.js

유저 프로필이미지 & 닉네임 수정
비밀번호 수정
-----
유저가 참여중인(참여예정, 완료) 챌린지 구현

[merge] mypage 수정기능

---

src/components/ChallengesInProgress.js
src/components/CompletedChallenge.js
src/components/MyPassword.js
src/components/UpcomingChallenge.js
src/redux/modules/mypage.js
src/shared/Cookie.js
src/shared/api.js

비밀번호 수정 후 input값 비우기 & 진행중,예정,완료 챌린지 로드

[merge] 비밀번호 수정 & 챌린지 로드

---

src/components/mainpage/Category.js
src/components/mypage/MyPieces.js
src/elements/Card.js
src/redux/modules/mypage.js
src/redux/modules/user.js
src/shared/api.js

- 리프레시 토큰 로그인 수정
- elements폴더 추가

Edit refreshToken login

---

src/elements/Card.js
src/elements/Image.js
src/elements/Tag.js
src/elements/index.js
src/pages/TestPage.js
src/redux/modules/user.js
src/shared/App.js
src/shared/api.js
src/shared/theme.js

-  Card, Image, Tag elements 만들고 공통으로 불러 쓰는 index.js 만들었습니다!
-  Mypage Point 쪽 서버에서 data get 해오는 코드 구현 완료 
=> 새로 고침 시 약간의 오류 생겨서 추후에 처리 해줘야 될 것 같아요!

Make elements - Card, Image, Tag

---

package.json
src/pages/Login.js
src/pages/Signup.js
src/redux/modules/user.js
src/shared/api.js
yarn.lock

[수정] 로그인 회원가입 formik , Yup 으로 수정

[수정] 로그인 회원가입 formik , Yup 으로 수정

---

src/elements/Button.js
src/elements/index.js
src/pages/Login.js
src/shared/theme.js

[추가] 버튼 엘리먼트 추가

---

src/components/mainpage/Category.js
src/components/mainpage/Info.js
src/components/mainpage/MainSlider.js
src/components/mainpage/Popular.js
src/components/mypage/ChallengesInProgress.js
src/elements/Button.js
src/elements/Card.js
src/elements/Tag.js
src/pages/ChallengeDetail.js
src/pages/Main.js

mainPage CSS 수정
배너는 추후에 이미지 전달받으면 수정

[merge] mainPage CSS

---

src/components/Search.js
src/components/challenge/CreateCertification.js
src/components/challengedetail/ChallengeInfo.js
src/components/challengedetail/ConditionBtn.js
src/components/challengedetail/PostList.js
src/components/challengedetail/ShotList.js
src/components/mypage/ChallengesInProgress.js
src/components/mypage/CompletedChallenge.js
src/components/mypage/MyPassword.js
src/components/mypage/MyPieces.js
src/components/mypage/UpcomingChallenge.js
src/elements/Button.js
src/elements/Card.js
src/elements/Image.js
src/elements/Input.js
src/elements/Tag.js
src/pages/ChallengeDetail.js
src/pages/Mypage.js
src/pages/Signup.js
src/redux/modules/mypage.js
src/redux/modules/post.js
src/shared/InfinityScroll.js
src/shared/theme.js

- 유저 상태에 따라 ChallengeDetail page에서 버튼 다르게 보여주는 조건 추가
- 원준님 ChallengeCreate page styling 수정한 것 merge 완료!

commit after merge with challengeCreate page

---

src/components/challenge/CreateCalendar.js
src/components/challenge/CreateImgSelect.js
src/components/challengedetail/ConditionBtn.js
src/components/challengedetail/ShotList.js
src/pages/ChallengeCreate.js
src/pages/SearchChallenge.js
src/redux/modules/post.js
src/shared/InfinityScroll.js

- 검색 페이지 & 기능 부분 merge 완료
- infinity scroll => 챌린지 detail페이지에서 인증샷 목록에 적용 완료

Pull request before starting chat 

---

src/components/challenge/CreateCalendar.js
src/pages/ChallengeCreate.js

[merge] 충돌수정

---

package.json
public/index.html
src/assets/images/icons/menubar.svg
src/components/Footer.js
src/components/Header.js
src/components/Sidebar.js
src/components/challengedetail/ChallengeInfo.js
src/components/challengedetail/ConditionBtn.js
src/components/challengedetail/PostList.js
src/components/challengedetail/PostWrite.js
src/components/challengedetail/PwdModal.js
src/components/challengedetail/ShotList.js
src/components/challengedetail/StateBox.js
src/components/chat/Chat.js
src/components/chat/MessageList.js
src/components/chat/MessageWrite.js
src/components/mainpage/MainSlider.js
src/pages/ChallengeCreate.js
src/pages/ChallengeDetail.js
src/pages/Main.js
src/redux/modules/chat.js
src/redux/modules/post.js
src/shared/api.js
src/shared/theme.js
yarn.lock

- 태현님이 직접 만든 슬라이더 적용됨
- mobile 헤더 틀 잡아놓음
- 챌린지 디테일 페이지 푸터랑 모달 제외하고 어느정도 완성

Media challenge detail

---

src/components/challenge/CreateCalendar.js
src/components/signup/WelcomeModal.js
src/pages/Login.js
src/pages/Signup.js
src/redux/modules/user.js

[merge] modal working

---

src/components/Footer.js
src/components/mainpage/Category.js
src/components/mainpage/MainSlider.js
src/components/mainpage/Popular.js
src/pages/Main.js

메인 페이지 메인 슬라이더
모바일 버전 카데고리별 챌린지 슬라이더
모바일 버전 HOT 챌린지 슬라이더
좌우 드래그 기능 추가

[feat] mainPage slide swipe 기능 추가

---

src/components/challenge/CreateCalendar.js
src/components/challenge/CreateCertification.js
src/components/challenge/CreateImgSelect.js
src/pages/ChallengeCreate.js

[style] challenge create

---

src/components/chat/Chat.js
src/components/chat/MessageList.js
src/components/mypage/ChallengesInProgress.js
src/elements/Card.js
src/elements/Image.js
src/pages/SearchChallenge.js

- Card element에서 사용하는 Image Element에 maxHeight props 추가!

[style] Edit Card Style

---

src/components/challenge/CreateCalendar.js
src/components/challenge/CreateCertification.js
src/components/challenge/CreateImgSelect.js
src/components/chat/Chat.js
src/pages/ChallengeCreate.js

[style] create challenge

---

src/components/challenge/PwdModal.js
src/components/challengedetail/PwdModal.js
src/components/challengedetail/StateBox.js
src/components/mainpage/Category.js
src/components/mainpage/Info.js
src/components/mypage/ChallengesInProgress.js
src/components/mypage/CompletedChallenge.js
src/components/mypage/UpcomingChallenge.js
src/elements/Card.js
src/elements/TagContainer.js
src/elements/index.js
src/pages/ChallengeCreate.js
src/pages/Main.js
src/pages/Mypage.js
src/pages/SearchChallenge.js
src/shared/Cookie.js

- 비밀번호 모달창 모바일 버전 수정 완료
- 로그아웃 기능 수정 완료
- 챌린지 검색 모바일 스타일 수정 완료

[error] Fix deleteCookie and SearchChallenge.js style

---

src/components/challenge/CreateCalendar.js
src/components/challenge/CreateCertification.js
src/components/challenge/CreateImgSelect.js
src/components/challenge/PwdModal.js
src/pages/ChallengeCreate.js
src/shared/style.css

[style] challenge update

---

src/pages/ChallengeEdit.js

[style] challengeEdit update

---

src/shared/style.css

[style]  Calendar update

---

src/pages/ChallengeCreate.js
src/pages/ChallengeEdit.js

[style] mobile guideline update

[style] mobile guideline update

---

src/components/challengedetail/ConditionBtn.js
src/components/challengedetail/PostList.js
src/components/challengedetail/PostWrite.js
src/components/chat/Chat.js
src/components/chat/ChatInfinityScroll.js
src/components/chat/MessageList.js
src/components/mainpage/Category.js
src/components/mypage/MyPieces.js
src/elements/Card.js
src/pages/ChallengeDetail.js
src/pages/Main.js
src/pages/Mypage.js
src/redux/configureStore.js
src/redux/modules/challengeDetail.js
src/redux/modules/chat.js
src/redux/modules/mypage.js
src/shared/api.js

- 채팅 무한스크롤 임시적 해결
- 주말 제외 인증하기 버튼 예외 처리 진행중
-

Infinity scroll chat

---

src/pages/ChallengeCreate.js
src/pages/ChallengeEdit.js

[style] update

---

src/components/signup/WelcomeModal.js

[style] welcome modal update

---

src/components/challengedetail/ConditionBtn.js
src/components/challengedetail/PostWrite.js
src/components/chat/MessageList.js
src/components/mainpage/MainSlider.js
src/components/mainpage/Popular.js
src/pages/Main.js
src/shared/InfinityScroll.js
src/shared/api.js
src/shared/theme.js

[style] CSS 수정

---

src/components/mainpage/Category.js
src/components/mainpage/Info.js
src/components/mainpage/MainSlider.js
src/components/mainpage/Popular.js
src/components/mypage/ChallengesInProgress.js
src/components/mypage/CompletedChallenge.js
src/components/mypage/MyPieces.js
src/components/mypage/UpcomingChallenge.js
src/elements/Card.js
src/pages/Mypage.js
src/redux/modules/mypage.js
src/shared/api.js

my page api 수정
card 수정
popular img 수정
main slider 모바일 버전일때 자동 넘김

[fix] 기능 수정

---

src/components/Footer.js
src/components/Header.js
src/components/Sidebar.js
src/components/challenge/CreateCalendar.js
src/components/challenge/CreateCertification.js
src/components/challengedetail/ChallengeInfo.js
src/components/challengedetail/PwdModal.js
src/components/mainpage/Category.js
src/components/mainpage/MainSlider.js
src/components/mainpage/Popular.js
src/pages/ChallengeCreate.js
src/pages/Main.js
src/pages/Mypage.js
src/pages/SearchChallenge.js
src/redux/modules/challengeDetail.js
src/redux/modules/main.js
src/shared/App.js
src/shared/api.js

search: (searchWords) => instance.get(`api/guest/search/1/${searchWords}`),
=> /api/guest/search/${searchWords}/1 변경
searchCategory: (categoryName) =>
instance.get(`/api/guest/challenge/category/1/${categoryName}`),
=> 삭제
searchAll: () => instance.get(`/api/guest/challenge-all/1`),
=> `/api/guest/search/${categoryName}/${period}/1` 변경
response tagList => tag로 변경에 따라 코드 수정

[fix] search api 변경중

---

src/pages/ChallengeCreate.js
src/pages/ChallengeEdit.js

[feedback] challenge textarea update

[feedback] challenge textarea update

---

src/components/Header.js
src/components/challengedetail/ChallengeInfo.js
src/components/challengedetail/ChallengeMember.js
src/components/challengedetail/ShotList.js
src/components/mainpage/MainSlider.js
src/pages/ChallengeDetail.js
src/redux/modules/challengeDetail.js
src/redux/modules/main.js

[error]Add Loader

---

src/components/challenge/CreateCalendar.js

[css] update challenge calendar

[css] update challenge calendar

---

src/components/Header.js
src/components/challenge/CreateCertification.js
src/components/challengedetail/ChallengeInfo.js
src/components/challengedetail/ShotList.js
src/components/chat/Chat.js
src/pages/Mypage.js
src/pages/SearchChallenge.js
src/redux/configureStore.js
src/redux/modules/challengeDetail.js
src/redux/modules/main.js
src/redux/modules/mypage.js
src/shared/api.js

기존 검색어로 검색 시 검색결과창에서 전체보기로 결과가 보였던것 수정

[merge] 검색 기능 수정

---

src/pages/ChallengeCreate.js
src/pages/ChallengeEdit.js
src/pages/GradePage.js

[css] ChallengeEdit css update

[css] ChallengeEdit css update

---

src/components/mainpage/Category.js
src/pages/SearchChallenge.js
src/redux/modules/main.js
src/shared/api.js

기존 searchFilter api로 전체 챌린지를 가져오는게 이상해서
전체 챌린지를 가져오는 api (allChallenge) 새로 생성 및 추가

[fix] get all challenge api 추가

---

src/components/Header.js
src/pages/SearchChallenge.js

[fix] search page 기능 수정

---

src/components/mainpage/Category.js
src/pages/SearchChallenge.js
src/redux/modules/main.js
src/shared/api.js

[merge] 검색결과창 수정

---

src/pages/ChallengeCreate.js
src/pages/ChallengeEdit.js

[style] css update

---

src/components/challenge/CreateCertification.js
src/components/challenge/CreateImgSelect.js
src/components/challengedetail/ChallengeInfo.js
src/components/challengedetail/ShotList.js
src/components/challengedetail/StateBox.js
src/components/mypage/ChallengesInProgress.js
src/components/mypage/CompletedChallenge.js
src/components/mypage/MyPieces.js
src/components/mypage/UpcomingChallenge.js
src/pages/ChallengeCreate.js
src/pages/ChallengeDetail.js
src/pages/ChallengeEdit.js
src/pages/GradePage.js
src/pages/LandingPage.js
src/pages/Login.js
src/pages/Mypage.js
src/pages/SearchChallenge.js
src/pages/Signup.js
yarn.lock

[css] cursor update

---

src/pages/ChallengeEdit.js

[css] challenge update

---

src/shared/style.css

[css] Calendar button

---

src/components/challenge/CreateCalendar.js
src/components/challenge/CreateImgSelect.js
src/pages/ChallengeCreate.js
src/pages/ChallengeEdit.js

challenge update
